### ISSUE TITLE
Proposition: Make Textinator Into a Generalized Extensible Clipboard Manipulation Tool

### ISSUE THREAD

**Issue by bwagner** [RhetTbull/textinator#20]
I often wish for additional features to Textinator's existing functionality, like:
- [titlecase](https://pypi.org/project/titlecase/) the contents of the clipboard, e.g. "the meaning of life" -> "The Meaning of Life"
- when the clipboard contains a filename, replace invalid/unwanted characters, e.g.:
  "\~/Documents/der frühling [Vol.2].pdf" -> "\~/Documents/der_fruehling_Vol_2.pdf"
- When copying text out of an Apple "Books" document, that app feels compelled to remind me that the text is copyrighted by appending a litany to what I had chosen to copy. In the case of program code that is particularly disruptive.  Textinator would offer to revert the clipboard contents to the originally intended. Example: Highlight and copy some code out of [Mark Lutz' "Programming Python, 4th edition"](https://learning-python.com/about-pp4e.html), p. 972:
```Python
import time
gmt = time.gmtime(time.time())
```
What ends up in your clipboard instead:
```Python
“import time
gmt = time.gmtime(time.time())”

Excerpt From
Programming Python
Mark Lutz
This material may be protected by copyright.
```

So, Textinator would become like a hub for clipboard manipulations of which its existing OCR-functionality is but a plugin.

Here's an example script I currently have in my `bin`-directory, which would become a plugin in this Textinator-hub:
```Python
#!/usr/bin/env python

from titlecase import titlecase
import pyperclip

pyperclip.copy(titlecase(pyperclip.paste()))
```

**Comment by RhetTbull** [comment]
Though it would be possible to extend Textinator to be a general purpose clipboard manager I see Textinator's functionality of "perform OCR on the clipboard" and other "manipulate the clipboard" as separate things. One easy solution would be to use [FastScripts](https://redsweater.com/fastscripts/), a Mac app for running scripts, as a way to do this as it wouldn't be specialized to just clipboard manipulation. FastScripts is commercial software but one I gladly pay for as it's quite useful. It can run AppleScripts or shell scripts (and if you add `#!/usr/local/bin/python3` or whatever your python path is to the top of the script and then `chmod u+x script.py`, your python script looks like a shell script to FastScripts and you can easily assign shortcuts to scripts and assign scripts to specific applications. For example, if you have a script you want to run only when using Safari, you can put it in the Safari folder and it only appears in the FastScripts menu when Safari is the front most application. FastScritps will look for scripts in `~/Library/Scripts` or `/Library/Scripts` by default but you can add other script locations. 

For general text cleaning, [Text Soap](https://textsoap.com/mac/) might be good but for the use cases you listed, a small python script that is called by FastScripts would work.

If you really do want to extend Textinator, it wouldn't be difficult to modify if you know some python (and if you're reading Mark Lutz's book, it sounds as if you may). Textinator includes a class for manipulating the cliboard, [pasteboard.py](https://github.com/RhetTbull/textinator/blob/main/src/pasteboard.py), which could be used by plugins. 

Here's an example of code from another project of mine that loads a function from a user supplied file at run time so that python can execute it. Textinator could look for python files in a specified folder and load a function then add it to the menu for a simple plugin system or you could use something like [pluggy](https://pypi.org/project/pluggy/) which I've used in another project. 

https://github.com/RhetTbull/osxphotos/blob/950260d46e1b5cdd003b58108a299f7262a41b05/osxphotos/utils.py#L452-L477

But really, I think the simplest thing to do is to write the functionality you want into simple scripts then use FastScripts to call these. For example, I use a script to "Convert clipboard to plain text" as I hate pasting rich text when I just wanted the raw text and I have this assigned to a hot key in FastScripts.

**Comment by bwagner** [comment]
Terrific, thanks a lot for these hints!
