### ISSUE TITLE
Add ability to override Dropbox's "Share screenshots and screen recordings" link sharing

### ISSUE THREAD

**Issue by joeld1** [RhetTbull/textinator#31]
Textinator doesn't OCR the text when Dropbox's "Share screenshots and screen recordings using Dropbox" setting is toggled on. Instead of getting a copy of the text found in the screenshot, I receive a copy of the Dropbox share url to the screenshot

Would it be possible to add the ability to override this feature? 

Just curious because it takes many clicks to toggle Dropbox's feature on/off.

Thank you!

![Screenshot 2024-04-28 at 8 08 05 AM](https://github.com/RhetTbull/textinator/assets/10216562/a85d2ae9-4757-4453-8b83-3c88123c48ca)

**Comment by RhetTbull** [comment]
>  I receive a copy of the Dropbox share url to the screenshot

That's exactly what you've told Dropbox to do. :-)

What exactly do you want to happen in this case? If the dropbox link sharing feature is something you use, then I assume you want Dropbox to put the link on the clipboard? But if Textinator was changed to override this, you would also get the detected text instead of the Dropbox link if there was text in the screenshot. Thus you would never be able to use the Dropbox share feature on a screenshot with text because the link would be overwritten by Textinator.

If you want to use the Dropbox feature perhaps a better alternative is to use a commercial app like TextSniper which lets you use a separate hot key to grab the text.

**Comment by joeld1** [comment]
Huh, I tested it again - sometimes the dropbox link gets stored, other times it's the image text.

How about this, would it be possible to keep a clipboard cache that stores the text of the previous OCR job? It would be super convenient in case any clipboard text gets overwritten immediately afterwards by another program.

**Comment by RhetTbull** [comment]
> How about this, would it be possible to keep a clipboard cache that stores the text of the previous OCR job? I

That's not a bad idea. You could do this with a clipboard management app but it should be easy to add a "Copy last text detection to clipboard" feature and maybe an option to pop up a window with the last detection.

**Comment by RhetTbull** [comment]
The next release includes a "Show Last Detected Text" menu option that opens a window with the text (and a default button that will copy it to the clipboard by simply pressing return or click the button)

**Comment by RhetTbull** [comment]
Released as v0.10.0

**Comment by joeld1** [comment]
Thanks again for this feature! It's super helpful!
